// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `objectDetectionCNN.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <objectDetectionCNN.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <Ice/Object.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __RoboCompobjectDetectionCNN__objectDetectionCNN__getLabelsFromImage_name = "getLabelsFromImage";

}

namespace Ice
{
}
::IceProxy::Ice::Object* ::IceProxy::RoboCompobjectDetectionCNN::upCast(::IceProxy::RoboCompobjectDetectionCNN::objectDetectionCNN* p) { return p; }

void
::IceProxy::RoboCompobjectDetectionCNN::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompobjectDetectionCNN::objectDetectionCNN>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::RoboCompobjectDetectionCNN::objectDetectionCNN;
        v->__copyFrom(proxy);
    }
}

void
IceProxy::RoboCompobjectDetectionCNN::objectDetectionCNN::getLabelsFromImage(const ::RoboCompobjectDetectionCNN::ColorSeq& image, ::Ice::Int rows, ::Ice::Int cols, ::RoboCompobjectDetectionCNN::ResultList& result, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __RoboCompobjectDetectionCNN__objectDetectionCNN__getLabelsFromImage_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__RoboCompobjectDetectionCNN__objectDetectionCNN__getLabelsFromImage_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::RoboCompobjectDetectionCNN::objectDetectionCNN* __del = dynamic_cast< ::IceDelegate::RoboCompobjectDetectionCNN::objectDetectionCNN*>(__delBase.get());
            __del->getLabelsFromImage(image, rows, cols, result, __ctx, __observer);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompobjectDetectionCNN::objectDetectionCNN::begin_getLabelsFromImage(const ::RoboCompobjectDetectionCNN::ColorSeq& image, ::Ice::Int rows, ::Ice::Int cols, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RoboCompobjectDetectionCNN__objectDetectionCNN__getLabelsFromImage_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompobjectDetectionCNN__objectDetectionCNN__getLabelsFromImage_name, __del, __cookie);
    try
    {
        __result->__prepare(__RoboCompobjectDetectionCNN__objectDetectionCNN__getLabelsFromImage_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(image);
        __os->write(rows);
        __os->write(cols);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::RoboCompobjectDetectionCNN::objectDetectionCNN::end_getLabelsFromImage(::RoboCompobjectDetectionCNN::ResultList& result, const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RoboCompobjectDetectionCNN__objectDetectionCNN__getLabelsFromImage_name);
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(result);
        __result->__endReadParams();
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

const ::std::string&
IceProxy::RoboCompobjectDetectionCNN::objectDetectionCNN::ice_staticId()
{
    return ::RoboCompobjectDetectionCNN::objectDetectionCNN::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::RoboCompobjectDetectionCNN::objectDetectionCNN::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::RoboCompobjectDetectionCNN::objectDetectionCNN);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::RoboCompobjectDetectionCNN::objectDetectionCNN::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::RoboCompobjectDetectionCNN::objectDetectionCNN);
}

::IceProxy::Ice::Object*
IceProxy::RoboCompobjectDetectionCNN::objectDetectionCNN::__newInstance() const
{
    return new objectDetectionCNN;
}

void
IceDelegateM::RoboCompobjectDetectionCNN::objectDetectionCNN::getLabelsFromImage(const ::RoboCompobjectDetectionCNN::ColorSeq& image, ::Ice::Int rows, ::Ice::Int cols, ::RoboCompobjectDetectionCNN::ResultList& result, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __RoboCompobjectDetectionCNN__objectDetectionCNN__getLabelsFromImage_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(image);
        __os->write(rows);
        __os->write(cols);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(result);
        __og.endReadParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

void
IceDelegateD::RoboCompobjectDetectionCNN::objectDetectionCNN::getLabelsFromImage(const ::RoboCompobjectDetectionCNN::ColorSeq& image, ::Ice::Int rows, ::Ice::Int cols, ::RoboCompobjectDetectionCNN::ResultList& result, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::RoboCompobjectDetectionCNN::ColorSeq& __p_image, ::Ice::Int __p_rows, ::Ice::Int __p_cols, ::RoboCompobjectDetectionCNN::ResultList& __p_result, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_image(__p_image),
            _m_rows(__p_rows),
            _m_cols(__p_cols),
            _m_result(__p_result)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::RoboCompobjectDetectionCNN::objectDetectionCNN* servant = dynamic_cast< ::RoboCompobjectDetectionCNN::objectDetectionCNN*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->getLabelsFromImage(_m_image, _m_rows, _m_cols, _m_result, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        const ::RoboCompobjectDetectionCNN::ColorSeq& _m_image;
        ::Ice::Int _m_rows;
        ::Ice::Int _m_cols;
        ::RoboCompobjectDetectionCNN::ResultList& _m_result;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __RoboCompobjectDetectionCNN__objectDetectionCNN__getLabelsFromImage_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(image, rows, cols, result, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

::Ice::Object* RoboCompobjectDetectionCNN::upCast(::RoboCompobjectDetectionCNN::objectDetectionCNN* p) { return p; }

namespace
{
const ::std::string __RoboCompobjectDetectionCNN__objectDetectionCNN_ids[2] =
{
    "::Ice::Object",
    "::RoboCompobjectDetectionCNN::objectDetectionCNN"
};

}

bool
RoboCompobjectDetectionCNN::objectDetectionCNN::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__RoboCompobjectDetectionCNN__objectDetectionCNN_ids, __RoboCompobjectDetectionCNN__objectDetectionCNN_ids + 2, _s);
}

::std::vector< ::std::string>
RoboCompobjectDetectionCNN::objectDetectionCNN::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__RoboCompobjectDetectionCNN__objectDetectionCNN_ids[0], &__RoboCompobjectDetectionCNN__objectDetectionCNN_ids[2]);
}

const ::std::string&
RoboCompobjectDetectionCNN::objectDetectionCNN::ice_id(const ::Ice::Current&) const
{
    return __RoboCompobjectDetectionCNN__objectDetectionCNN_ids[1];
}

const ::std::string&
RoboCompobjectDetectionCNN::objectDetectionCNN::ice_staticId()
{
    return __RoboCompobjectDetectionCNN__objectDetectionCNN_ids[1];
}

::Ice::DispatchStatus
RoboCompobjectDetectionCNN::objectDetectionCNN::___getLabelsFromImage(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::RoboCompobjectDetectionCNN::ColorSeq image;
    ::Ice::Int rows;
    ::Ice::Int cols;
    __is->read(image);
    __is->read(rows);
    __is->read(cols);
    __inS.endReadParams();
    ::RoboCompobjectDetectionCNN::ResultList result;
    getLabelsFromImage(image, rows, cols, result, __current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(result);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __RoboCompobjectDetectionCNN__objectDetectionCNN_all[] =
{
    "getLabelsFromImage",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

::Ice::DispatchStatus
RoboCompobjectDetectionCNN::objectDetectionCNN::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__RoboCompobjectDetectionCNN__objectDetectionCNN_all, __RoboCompobjectDetectionCNN__objectDetectionCNN_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __RoboCompobjectDetectionCNN__objectDetectionCNN_all)
    {
        case 0:
        {
            return ___getLabelsFromImage(in, current);
        }
        case 1:
        {
            return ___ice_id(in, current);
        }
        case 2:
        {
            return ___ice_ids(in, current);
        }
        case 3:
        {
            return ___ice_isA(in, current);
        }
        case 4:
        {
            return ___ice_ping(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
RoboCompobjectDetectionCNN::objectDetectionCNN::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
RoboCompobjectDetectionCNN::objectDetectionCNN::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
RoboCompobjectDetectionCNN::__patch(objectDetectionCNNPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::RoboCompobjectDetectionCNN::objectDetectionCNNPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::RoboCompobjectDetectionCNN::objectDetectionCNN::ice_staticId(), v);
    }
}
